create table RawQualityInspection(
Inspection_ID varchar,
Inspection_Date varchar,
Inspection_Time varchar,
Year int,
Month int,
Order_ID varchar,
Product_ID varchar,
Product_Name varchar,
Batch_Number varchar,
Inspector_ID varchar,
Inspector_Name varchar,
InspectorDepartment varchar,
Department varchar,
Factory_ID varchar,
Factory_Name varchar,
Assembly_Line_ID varchar,
Assembly_Line_Name varchar,
Quantity_Inspected int,
Quantity_Defective int,
Defect_Rate float,
Sample_Size int,
Defect_Type varchar,
Defect_Code varchar,
Defect_Severity varchar,
Defect_Description varchar,
Dimension1 float,
Dimension2 float,
Weight float,
Visual_Quality varchar,
Functional_Test varchar,
Inspection_Status varchar,
Inspection_Result varchar,
Rework_Required varchar,
Approved varchar,
ApprovedBy varchar,
Notes varchar,
PhotoPath varchar
);
select * from RawQualityInspection;

copy RawQualityInspection from 'D:\MOCK1\RawQualityInspection.csv' delimiter ',' csv header;