create table RawSupplyChain(
InventoryID varchar,
InventoryDate varchar,
Year int,
Month int,
PartID varchar,
PartName varchar,
PartCode varchar,
PartCategory varchar,
PartDescription varchar,
SupplierID varchar,
SupplierName varchar,
SupplierCity varchar,
SupplierCountry varchar,
SupplierRating float,
WarehouseID varchar,
WarehouseName varchar,
WarehouseLocation varchar,
WarehouseCity varchar,
QuantityOnHand int,
QuantityReserved int,
QuantityDamaged int,
AvailableQuantity int,
ReorderLevel int,
ReorderQuantity int,
LeadTimeDays int,
UnitCost float,
TotalCost float,
SupplierLeadTime int,
ReceiveDate varchar,
InvoiceNumber varchar,
InvoiceAmount float,
Status varchar,
ExpiryDate varchar,
StorageLocation varchar,
LastStockUpdate varchar,
Notes varchar
);
select * from RawSupplyChain;

copy RawSupplyChain from 'D:\MOCK1\RawSupplyChain.csv' delimiter ',' csv header;