create table RawProductionOrder
(order_id varchar,
order_date varchar,
order_time varchar,
year int,
month int,
month_name varchar,
quarter varchar,
day_ofweek varchar,
customer_id varchar,
customer_name varchar,
customer_type varchar,
customer_city varchar,
customer_country varchar,
contact_email varchar,
contact_phone varchar,
product_id varchar,
product_name varchar,
product_code varchar,
product_category varchar,
product_sub_category varchar,
product_description varchar,
order_quantity float,
unit_price float,
total_price float,
delivery_date varchar,
delivery_location varchar,
factory_id varchar,
factory_name varchar,
factory_location varchar,
factory_city varchar,
factory_country varchar,
factory_capacity varchar,
assembly_line_id varchar,
assembly_line_name varchar,
line_type varchar,
line_capacity varchar,
current_load varchar,
scheduled_start_date varchar,
actual_start_date varchar,
scheduled_end_date varchar,
actual_end_date varchar,
production_status varchar,
completion_percent int,
quality_score float,
defects int,
rework_required varchar,
scheduled_delivery varchar,
actual_delivery varchar,
delivery_status varchar,
delay_days varchar,
note varchar
);
select * from RawProductionOrder;
	
copy RawProductionOrder from 'D:\MOCK1\RawProductionOrders.csv' DELIMITER ',' csv header;


